<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:ntu_csie_selab_inventorysystem_model_ItemHistory="http://140.112.90.144:7122/InventorySystemBackendMarksTonyModify/ntu/csie/selab/inventorysystem/model/ItemHistory" xmlns:selfNameSpace="http://140.112.90.144:7122/InventorySystemBackendMarksTonyModify/ntu/csie/selab/inventorysystem/model/ItemHistory/getPrice" xmlns:wsdlrestful="http://schemas.xmlsoap.org/wsdl/restful/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="http://140.112.90.144:7122/InventorySystemBackendMarksTonyModify/ntu/csie/selab/inventorysystem/model/ItemHistory/getPrice">
  <wsdl:types>
    <xsd:schema elementFormDefault="qualified"/>
  </wsdl:types>
  <wsdl:message name="getPriceRequest">
    <wsdl:part element="ntu_csie_selab_inventorysystem_model_ItemHistory:ntu_csie_selab_inventorysystem_model_ItemHistory" name="self" wsdlrestful:contentType="application/json" wsdlrestful:requestType="get"/>
  </wsdl:message>
  <wsdl:message name="getPriceResponse">
    <wsdl:part name="serviceResult" type="xsd:double" wsdlrestful:contentType="application/json"/>
    <wsdl:part name="standardOutput" type="xsd:string" wsdlrestful:contentType="application/json"/>
  </wsdl:message>
  <wsdl:portType name="getPricePort">
    <wsdl:operation name="getPrice">
      <wsdl:output message="selfNameSpace:getPriceResponse" name="out"/>
      <wsdl:input message="selfNameSpace:getPriceRequest" name="in"/>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:service name="getPriceService">
    <wsdlrestful:address method="get" url="http://140.112.90.144:7122/InventorySystemBackendMarksTonyModify/ntu/csie/selab/inventorysystem/model/ItemHistory/getPrice"/>
  </wsdl:service>
  <wsdl:import location="http://140.112.90.144/wsdl/InventorySystemBackendMarksTonyModify/ntu/csie/selab/inventorysystem/model/ItemHistory.wsdl" namespace="http://140.112.90.144:7122/InventorySystemBackendMarksTonyModify/ntu/csie/selab/inventorysystem/model/ItemHistory"/>
</wsdl:definitions>
