<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:ntu_csie_selab_inventorysystem_model_ItemHistory="http://140.112.90.144:7122/InventorySystemBackendMarksTonyModify/ntu/csie/selab/inventorysystem/model/ItemHistory" xmlns:ntu_csie_selab_inventorysystem_model_ItemHistoryEvent="http://140.112.90.144:7122/InventorySystemBackendMarksTonyModify/ntu/csie/selab/inventorysystem/model/ItemHistoryEvent" xmlns:selfNameSpace="http://140.112.90.144:7122/InventorySystemBackendMarksTonyModify/ntu/csie/selab/inventorysystem/model/ItemHistory/setEvent-ntu_csie_selab_inventorysystem_model_ItemHistoryEvent" xmlns:wsdlrestful="http://schemas.xmlsoap.org/wsdl/restful/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="http://140.112.90.144:7122/InventorySystemBackendMarksTonyModify/ntu/csie/selab/inventorysystem/model/ItemHistory/setEvent-ntu_csie_selab_inventorysystem_model_ItemHistoryEvent">
  <wsdl:types>
    <xsd:schema elementFormDefault="qualified"/>
  </wsdl:types>
  <wsdl:message name="setEventRequest">
    <wsdl:part element="ntu_csie_selab_inventorysystem_model_ItemHistory:ntu_csie_selab_inventorysystem_model_ItemHistory" name="self" wsdlrestful:contentType="application/json" wsdlrestful:requestType="get"/>
    <wsdl:part element="ntu_csie_selab_inventorysystem_model_ItemHistoryEvent:ntu_csie_selab_inventorysystem_model_ItemHistoryEvent" name="event" wsdlrestful:contentType="application/json" wsdlrestful:requestType="get"/>
  </wsdl:message>
  <wsdl:message name="setEventResponse">
    <wsdl:part name="standardOutput" type="xsd:string" wsdlrestful:contentType="application/json"/>
  </wsdl:message>
  <wsdl:portType name="setEventPort">
    <wsdl:operation name="setEvent">
      <wsdl:output message="selfNameSpace:setEventResponse" name="out"/>
      <wsdl:input message="selfNameSpace:setEventRequest" name="in"/>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:service name="setEventService">
    <wsdlrestful:address method="get" url="http://140.112.90.144:7122/InventorySystemBackendMarksTonyModify/ntu/csie/selab/inventorysystem/model/ItemHistory/setEvent-ntu_csie_selab_inventorysystem_model_ItemHistoryEvent"/>
  </wsdl:service>
  <wsdl:import location="http://140.112.90.144/wsdl/InventorySystemBackendMarksTonyModify/ntu/csie/selab/inventorysystem/model/ItemHistory.wsdl" namespace="http://140.112.90.144:7122/InventorySystemBackendMarksTonyModify/ntu/csie/selab/inventorysystem/model/ItemHistory"/>
  <wsdl:import location="http://140.112.90.144/wsdl/InventorySystemBackendMarksTonyModify/ntu/csie/selab/inventorysystem/model/ItemHistoryEvent.wsdl" namespace="http://140.112.90.144:7122/InventorySystemBackendMarksTonyModify/ntu/csie/selab/inventorysystem/model/ItemHistoryEvent"/>
</wsdl:definitions>
