<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:ntu_csie_selab_inventorysystem_model_Acquisition="http://140.112.90.144:7122/InventorySystemBackendMarksTonyModify/ntu/csie/selab/inventorysystem/model/Acquisition" xmlns:ntu_csie_selab_inventorysystem_model_AcquisitionType="http://140.112.90.144:7122/InventorySystemBackendMarksTonyModify/ntu/csie/selab/inventorysystem/model/AcquisitionType" xmlns:selfNameSpace="http://140.112.90.144:7122/InventorySystemBackendMarksTonyModify/ntu/csie/selab/inventorysystem/model/Acquisition/setType-ntu_csie_selab_inventorysystem_model_AcquisitionType" xmlns:wsdlrestful="http://schemas.xmlsoap.org/wsdl/restful/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="http://140.112.90.144:7122/InventorySystemBackendMarksTonyModify/ntu/csie/selab/inventorysystem/model/Acquisition/setType-ntu_csie_selab_inventorysystem_model_AcquisitionType">
  <wsdl:types>
    <xsd:schema elementFormDefault="qualified"/>
  </wsdl:types>
  <wsdl:message name="setTypeRequest">
    <wsdl:part element="ntu_csie_selab_inventorysystem_model_Acquisition:ntu_csie_selab_inventorysystem_model_Acquisition" name="self" wsdlrestful:contentType="application/json" wsdlrestful:requestType="get"/>
    <wsdl:part element="ntu_csie_selab_inventorysystem_model_AcquisitionType:ntu_csie_selab_inventorysystem_model_AcquisitionType" name="type" wsdlrestful:contentType="application/json" wsdlrestful:requestType="get"/>
  </wsdl:message>
  <wsdl:message name="setTypeResponse">
    <wsdl:part name="standardOutput" type="xsd:string" wsdlrestful:contentType="application/json"/>
  </wsdl:message>
  <wsdl:portType name="setTypePort">
    <wsdl:operation name="setType">
      <wsdl:output message="selfNameSpace:setTypeResponse" name="out"/>
      <wsdl:input message="selfNameSpace:setTypeRequest" name="in"/>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:service name="setTypeService">
    <wsdlrestful:address method="get" url="http://140.112.90.144:7122/InventorySystemBackendMarksTonyModify/ntu/csie/selab/inventorysystem/model/Acquisition/setType-ntu_csie_selab_inventorysystem_model_AcquisitionType"/>
  </wsdl:service>
  <wsdl:import location="http://140.112.90.144/wsdl/InventorySystemBackendMarksTonyModify/ntu/csie/selab/inventorysystem/model/Acquisition.wsdl" namespace="http://140.112.90.144:7122/InventorySystemBackendMarksTonyModify/ntu/csie/selab/inventorysystem/model/Acquisition"/>
  <wsdl:import location="http://140.112.90.144/wsdl/InventorySystemBackendMarksTonyModify/ntu/csie/selab/inventorysystem/model/AcquisitionType.wsdl" namespace="http://140.112.90.144:7122/InventorySystemBackendMarksTonyModify/ntu/csie/selab/inventorysystem/model/AcquisitionType"/>
</wsdl:definitions>
