<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:java_util_List="http://140.112.90.144:7122/java/util/List" xmlns:ntu_csie_selab_inventorysystem_model_User="http://140.112.90.144:7122/InventorySystemBackendMarksTonyModify/ntu/csie/selab/inventorysystem/model/User" xmlns:selfNameSpace="http://140.112.90.144:7122/InventorySystemBackendMarksTonyModify/ntu/csie/selab/inventorysystem/model/User/setTokens-java_util_List" xmlns:wsdlrestful="http://schemas.xmlsoap.org/wsdl/restful/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="http://140.112.90.144:7122/InventorySystemBackendMarksTonyModify/ntu/csie/selab/inventorysystem/model/User/setTokens-java_util_List">
  <wsdl:types>
    <xsd:schema elementFormDefault="qualified"/>
  </wsdl:types>
  <wsdl:message name="setTokensRequest">
    <wsdl:part element="ntu_csie_selab_inventorysystem_model_User:ntu_csie_selab_inventorysystem_model_User" name="self" wsdlrestful:contentType="application/json" wsdlrestful:requestType="get"/>
    <wsdl:part element="java_util_List:java_util_List" name="tokens" wsdlrestful:contentType="application/json" wsdlrestful:requestType="get"/>
  </wsdl:message>
  <wsdl:message name="setTokensResponse">
    <wsdl:part name="standardOutput" type="xsd:string" wsdlrestful:contentType="application/json"/>
  </wsdl:message>
  <wsdl:portType name="setTokensPort">
    <wsdl:operation name="setTokens">
      <wsdl:output message="selfNameSpace:setTokensResponse" name="out"/>
      <wsdl:input message="selfNameSpace:setTokensRequest" name="in"/>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:service name="setTokensService">
    <wsdlrestful:address method="get" url="http://140.112.90.144:7122/InventorySystemBackendMarksTonyModify/ntu/csie/selab/inventorysystem/model/User/setTokens-java_util_List"/>
  </wsdl:service>
  <wsdl:import location="http://140.112.90.144/wsdl/InventorySystemBackendMarksTonyModify/ntu/csie/selab/inventorysystem/model/User.wsdl" namespace="http://140.112.90.144:7122/InventorySystemBackendMarksTonyModify/ntu/csie/selab/inventorysystem/model/User"/>
  <wsdl:import location="http://140.112.90.144/wsdl/java/util/List.wsdl" namespace="http://140.112.90.144:7122/java/util/List"/>
</wsdl:definitions>
