<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:ntu_csie_selab_inventorysystem_model_User="http://140.112.90.144:7122/InventorySystemBackendMarksTonyModify/ntu/csie/selab/inventorysystem/model/User" xmlns:selfNameSpace="http://140.112.90.144:7122/InventorySystemBackendMarksTonyModify/ntu/csie/selab/inventorysystem/model/User/setUsername-java_lang_String" xmlns:wsdlrestful="http://schemas.xmlsoap.org/wsdl/restful/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="http://140.112.90.144:7122/InventorySystemBackendMarksTonyModify/ntu/csie/selab/inventorysystem/model/User/setUsername-java_lang_String">
  <wsdl:types>
    <xsd:schema elementFormDefault="qualified"/>
  </wsdl:types>
  <wsdl:message name="setUsernameRequest">
    <wsdl:part element="ntu_csie_selab_inventorysystem_model_User:ntu_csie_selab_inventorysystem_model_User" name="self" wsdlrestful:contentType="application/json" wsdlrestful:requestType="get"/>
    <wsdl:part name="username" type="xsd:string" wsdlrestful:contentType="application/json" wsdlrestful:requestType="get"/>
  </wsdl:message>
  <wsdl:message name="setUsernameResponse">
    <wsdl:part name="standardOutput" type="xsd:string" wsdlrestful:contentType="application/json"/>
  </wsdl:message>
  <wsdl:portType name="setUsernamePort">
    <wsdl:operation name="setUsername">
      <wsdl:output message="selfNameSpace:setUsernameResponse" name="out"/>
      <wsdl:input message="selfNameSpace:setUsernameRequest" name="in"/>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:service name="setUsernameService">
    <wsdlrestful:address method="get" url="http://140.112.90.144:7122/InventorySystemBackendMarksTonyModify/ntu/csie/selab/inventorysystem/model/User/setUsername-java_lang_String"/>
  </wsdl:service>
  <wsdl:import location="http://140.112.90.144/wsdl/InventorySystemBackendMarksTonyModify/ntu/csie/selab/inventorysystem/model/User.wsdl" namespace="http://140.112.90.144:7122/InventorySystemBackendMarksTonyModify/ntu/csie/selab/inventorysystem/model/User"/>
</wsdl:definitions>
