<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:java_util_List="http://140.112.90.144:7122/java/util/List" xmlns:ntu_csie_selab_inventorysystem_service_ItemService="http://140.112.90.144:7122/InventorySystemBackendMarksTonyModify/ntu/csie/selab/inventorysystem/service/ItemService" xmlns:selfNameSpace="http://140.112.90.144:7122/InventorySystemBackendMarksTonyModify/ntu/csie/selab/inventorysystem/service/ItemService/itemHierarchyLeafList-java_lang_Integer-java_lang_Integer-java_lang_Integer" xmlns:wsdlrestful="http://schemas.xmlsoap.org/wsdl/restful/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="http://140.112.90.144:7122/InventorySystemBackendMarksTonyModify/ntu/csie/selab/inventorysystem/service/ItemService/itemHierarchyLeafList-java_lang_Integer-java_lang_Integer-java_lang_Integer">
  <wsdl:types>
    <xsd:schema elementFormDefault="qualified"/>
  </wsdl:types>
  <wsdl:message name="itemHierarchyLeafListRequest">
    <wsdl:part element="ntu_csie_selab_inventorysystem_service_ItemService:ntu_csie_selab_inventorysystem_service_ItemService" name="self" wsdlrestful:contentType="application/json" wsdlrestful:requestType="get"/>
    <wsdl:part name="did" type="xsd:integer" wsdlrestful:contentType="application/json" wsdlrestful:requestType="get"/>
    <wsdl:part name="cid" type="xsd:integer" wsdlrestful:contentType="application/json" wsdlrestful:requestType="get"/>
    <wsdl:part name="scid" type="xsd:integer" wsdlrestful:contentType="application/json" wsdlrestful:requestType="get"/>
  </wsdl:message>
  <wsdl:message name="itemHierarchyLeafListResponse">
    <wsdl:part element="java_util_List:java_util_List" name="serviceResult" wsdlrestful:contentType="application/json"/>
    <wsdl:part name="standardOutput" type="xsd:string" wsdlrestful:contentType="application/json"/>
  </wsdl:message>
  <wsdl:portType name="itemHierarchyLeafListPort">
    <wsdl:operation name="itemHierarchyLeafList">
      <wsdl:output message="selfNameSpace:itemHierarchyLeafListResponse" name="out"/>
      <wsdl:input message="selfNameSpace:itemHierarchyLeafListRequest" name="in"/>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:service name="itemHierarchyLeafListService">
    <wsdlrestful:address method="get" url="http://140.112.90.144:7122/InventorySystemBackendMarksTonyModify/ntu/csie/selab/inventorysystem/service/ItemService/itemHierarchyLeafList-java_lang_Integer-java_lang_Integer-java_lang_Integer"/>
  </wsdl:service>
  <wsdl:import location="http://140.112.90.144/wsdl/InventorySystemBackendMarksTonyModify/ntu/csie/selab/inventorysystem/service/ItemService.wsdl" namespace="http://140.112.90.144:7122/InventorySystemBackendMarksTonyModify/ntu/csie/selab/inventorysystem/service/ItemService"/>
  <wsdl:import location="http://140.112.90.144/wsdl/java/util/List.wsdl" namespace="http://140.112.90.144:7122/java/util/List"/>
</wsdl:definitions>
